version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/node_modules # evita sobrescribir los node_modules dentro del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true
